steps:
  # Step 1: Install dependencies and run tests
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['test', '--', '--passWithNoTests']  # Avoid failure if no tests exist

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/midterm-451519/rahul-100953252/app:${SHORT_SHA}', 
      '.'
    ]
    
  # Step 3: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/midterm-451519/rahul-100953252/app:${SHORT_SHA}'
    ]
  
  # Step 4: Deploy to Cloud Run using gcloud CLI
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy assignment2 \
          --image=us-central1-docker.pkg.dev/midterm-451519/rahul-100953252/app:${SHORT_SHA} \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
          --port=8080  # Ensure it listens on the correct port

  # Step 5: Verify the deployment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Cloud Run service URL: $(gcloud run services describe assignment2 --region=us-central1 --format='value(status.url)')"

images:
  - 'us-central1-docker.pkg.dev/midterm-451519/rahul-100953252/app:${SHORT_SHA}'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
