steps:
  # Step 1: Install dependencies and run tests
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['test']  # Run your tests using npm (make sure you have a test script defined in package.json)

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/cloud-infrastructure-448600/anish-100890955/assignment2:${SHORT_SHA}', 
      '.'
    ]
    
  # Step 3: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/cloud-infrastructure-448600/anish-100890955/assignment2:${SHORT_SHA}'
    ]
  
  # Step 4: Deploy to Cloud Run using gcloud CLI
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'assignment2'  # Cloud Run service name
      - '--image'
      - 'us-central1-docker.pkg.dev/cloud-infrastructure-448600/anish-100890955/assignment2:${SHORT_SHA}'
      - '--region'
      - 'us-central1'  # Region for Cloud Run
      - '--allow-unauthenticated'  # Make service publicly accessible

images:
  - 'us-central1-docker.pkg.dev/cloud-infrastructure-448600/anish-100890955/assignment2:${SHORT_SHA}'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
